# See https://github.com/troessner/reek#configuration-options
---

### Generic smell configuration

detectors:
    # https://github.com/troessner/reek/blob/master/docs/Utility-Function.md#configuration
    UtilityFunction:
        public_methods_only: true
        exclude: ['RSpecHelper']
    DataClump:
        exclude: ['RSpecHelper']
    # https://github.com/troessner/reek/blob/master/docs/Uncommunicative-Module-Name.md#configuration
    UncommunicativeModuleName:
        accept: ['APIv']
    # https://github.com/troessner/reek/blob/master/docs/Feature-Envy.md#configuration
    FeatureEnvy:
        exclude: ['Sanchin::User#to_json']
    # https://github.com/troessner/reek/blob/v5.3.2/docs/Too-Many-Statements.md#configuration
    TooManyStatements:
        max_statements: 8
    # https://github.com/troessner/reek/blob/master/docs/Instance-Variable-Assumption.md#configuration
    InstanceVariableAssumption:
        exclude: ['/^Sanchin::.*?::Transactions::/']
    # https://github.com/troessner/reek/blob/v5.3.2/docs/Control-Parameter.md#configuration
    ControlParameter:
        exclude: ['/^Sanchin::.*?::Transactions::/']

### Excluding directories

# Directories and files below will not be scanned at all
exclude_paths:
    - vendor/
