require: rubocop-performance
# see https://rubocop.readthedocs.io/en/latest/configuration/
AllCops:
    TargetRubyVersion: 2.5
    Exclude:
        - '.git/**/*'
        - 'bin/*'
        - 'node_modules/**/*'
        - 'spec/spec_helper.rb'
        - 'vendor/**/*'
    # Style guide URLs are not displayed in offense messages by default. Change
    # behavior by overriding `DisplayStyleGuide`, or by giving the
    # `-S/--display-style-guide` option.
    DisplayStyleGuide: true
    # Extra details are not displayed in offense messages by default. Change
    # behavior by overriding ExtraDetails, or by giving the
    # `-E/--extra-details` option.
    ExtraDetails: true

# Sometimes there is no choice.
Metrics/LineLength:
    Max: 100
    Exclude:
        - 'app/api/**/*'
Metrics/ClassLength:
    Exclude:
        - 'app/api/**/*'
Metrics/BlockLength:
    Exclude:
        - 'app/api/**/*'
        - 'spec/**/*' # top-level describe RSpec block can be very long.

# We like to use "transform(v) rescue v" patterns for coercion.
Style/RescueModifier:
    Exclude:
        - 'app/lib/types.rb'
        - 'app/api/*/help.rb'

# ignorance can be a bliss.
Style/RescueStandardError:
    Exclude:
        - 'app/concepts/*/transactions/*'
